# XSEMA NFT Analytics Engine - Production Docker Compose
version: '3.8'

services:
  # Main XSEMA NFT Analytics Engine
  xsema-engine:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - PORT=8000
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - xsema-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # PostgreSQL Database (Optional - for future use)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: xsema_analytics
      POSTGRES_USER: xsema_user
      POSTGRES_PASSWORD: xsema_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - xsema-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xsema_user -d xsema_analytics"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis Cache (Optional - for future use)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - xsema-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  xsema-network:
    driver: bridge
