[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install fastapi uvicorn"]

[start]
cmd = "python -c \"import uvicorn; from fastapi import FastAPI; app = FastAPI(); app.add_api_route('/', lambda: 'XSEMA Running'); app.add_api_route('/health', lambda: {'status': 'healthy'}); uvicorn.run(app, host='0.0.0.0', port=int('$PORT' or '8000'))\""
